### ISSUE TITLE
[Bug] Failing GitHub Actions causing skipped suggestions

### ISSUE THREAD

**Issue by cnotin** [merill/aka#115]
### Bug details

I suggested a couple of links today in a very short time frame and I noticed that some GitHub Actions jobs failed, for example: https://github.com/merill/aka/actions/runs/4925967498
It's a git issue since I suppose that the repo was updated by another job between the pull and the push:
```
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

And in the end the submitted link is skipped which is sad :(

Btw, thanks for this useful tool and for sharing on Twitter the interesting processes behind it ;)

**Comment by cnotin** [comment]
Bad bot 😅 you should have ignored this 😉

**Comment by merill** [comment]
I have fixed this now!

**Comment by cnotin** [comment]
Thanks :) should we resubmit all jobs that failed?

**Comment by cnotin** [comment]
Looks like it isn't necessary :)

**Comment by merill** [comment]
Yes I imported the missing ones.
