### ISSUE TITLE
Planning your Cloud HR integration with Azure AD

### ISSUE THREAD

**Issue by cmmdesai** [merill/aka#117]
### Aka.ms link name

CloudHRDeploymentPlan

### Category (Optional. Select None to auto-select)

azuread

**Comment by merill** [comment]
Thank you for submitting [aka.ms/CloudHRDeploymentPlan](https://aka.ms/CloudHRDeploymentPlan). Your link already exists at [akaSearch.net](https://akasearch.net). 🙏✅
