### ISSUE TITLE
New aka.ms link 

### ISSUE THREAD

**Issue by saveman71** [merill/aka#35]
### Aka.ms link name

download

### Category (Optional. Select None to auto-select)

None

**Comment by merill** [comment]
Thank you for submitting an aka.ms link. Unfortunately the link [https://aka.ms/download](https://aka.ms/download) is not a valid aka.ms link. If you believe this is a mistake, it could be a problem with the automated script. Please reach out to me at https://twitter.com/merill and let me know. Thanks!
