### ISSUE TITLE
[Request] Please add an API for new submissions

### ISSUE THREAD

**Issue by johngagefaulkner** [merill/aka#599]
I'm thinking something like `POST` to `/api/v1/links` or `/api/v1/config` that accepts a JSON body (must match the schema mentioned in the README) → ensure link doesn't already exist → either inform user the aka.ms link already exists OR create a new entry for the link and return success.

**Comment by johngagefaulkner** [comment]
I have a very long list of aka.ms links that I created a long time ago (not knowing this website existed) and it would be tedious to manually check if each one exists and create an issue if not.

**Comment by merill** [comment]
Hi John, you can use the GitHub api to submit each issue. The workflow that I have behind the scenes will validate the link and add it.

See this PowerShell module https://github.com/microsoft/PowerShellForGitHub

Here is the rest api https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue
