### ISSUE TITLE
New aka.ms link 

### ISSUE THREAD

**Issue by TheCloudScout** [merill/aka#94]
### Aka.ms link name

koos

### Category (Optional. Select None to auto-select)

azure

**Comment by TheCloudScout** [comment]
Category should be "Security" of perhaps "Microsoft 365 Defender" but that wasn't an option.

**Comment by merill** [comment]
Thank you for submitting [aka.ms/koos](https://aka.ms/koos). Your link already exists at [akaSearch.net](https://akasearch.net). 🙏✅
